version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '5998:80'
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 360; docker restart nginx-web-1; done"]
    restart: unless-stopped
