version: '3'

services:
  apache:
    build: .
    ports:
      - "5999:80"
    volumes:
      - ./src:/var/www/html/
    restart: unless-stopped
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 360; docker restart apache-apache-1; done"]
    restart: unless-stopped
